export const LABELS = {
  TITLE: "AVConnect",
  SAVE: "Save",
  SAVE_SUCCESS: "Save was successful",
  SAVE_FAILED: "Something went wrong while saving",
  LOGIN_OR_REGISTER: "Login or register",
  // Search Users
  SEARCH_RESULTS_FOR: "Search results for",
  SEARCH_NO_RESULTS_FOR: "No results found for",
  SEARCH_FOR: "Search for people",
  SEARCH_TEXT: "Search for someone you know..",
  SEARCH_NO_RESULTS: "No results found",
  SEARCH_ALL_RESULTS: "View all results",
  // Share Profile
  SHARE_PROFILE: "Share profile",
  COPY_PROFILE_LINK: "Copy profile link",
  // Image Upload Labels
  BACKGROUND_IMAGE_CROPPER_TITLE: "Background Image",
  DISPLAY_PICTURE_CROPPER_TITLE: "Display Picture",
  IMAGE_CROPPER_MESSAGE: "Drag around to reposition photo",
  USER_IMAGE_CHOOSE_IMAGE: "Choose Image",
  USER_IMAGE_CHANGE_IMAGE: "Change Image",
  USER_IMAGE_APPLY: "Apply",
  USER_IMAGE_REMOVE: "Remove",
  // About User labels
  ADD_SUMMARY: "Add Summary",
  ABOUT_FIELD_LABEL: "About",
  ABOUT_EDIT_TITLE: "About you",
  ABOUT_HEADLINE: "Lets add a few words about you",
  ABOUT_PLACEHOLDER:
    "You can write about your years of experience, industry, or skills. People also talk about their achievements or previous job experiences.",
  // User Skills Labels
  SKILLS_TITLE: "Skills",
  ADD_SKILLS: "Add Skills",
  EDIT_SKILLS: "Edit Skills",
  GIVEN_ENDORSEMENT: "given ensorement for this skill",
  ENDORSEMENT_HAVE: "have",
  ENDORSEMENT_HAS: "has",
  ENDORSEMENT_YOU: "You",
  ENDORSEMENT_AND: "and",
  ENDORSEMENT_CONNECTIONS: "connections",
  ADD_SKILL: "Add",
  MAX_SKILL_LIMIT: "Maximum number of skills you can add are",
  SHOW_MORE_SKILLS: "Show more",
  SHOW_LESS_SKILLS: "Show less",
};
