export const SKILLS_LIST = [
  "3D Modelling",
  "AR Designer",
  "Acting",
  "Animation",
  "CG Production",
  "Cartoon Drawing",
  "Casting Direction",
  "Cinematography",
  "Concept Designing",
  "Concierge",
  "Conference Planning",
  "Content Writing",
  "Convention Planning",
  "Copywriting",
  "Costume designing",
  "Dancing",
  "Event Analysis",
  "Event Coordination",
  "Event Operations Management",
  "Event Planning",
  "Event Reception",
  "Exhibition Coordination",
  "FX Direction",
  "Fashion Modelling",
  "Field Events Management",
  "Film Direction",
  "Film Distribution",
  "Film Droduction",
  "Film Publishing",
  "Film critique",
  "Game AI engineering",
  "Game Designing",
  "Game Journalism",
  "Game Production",
  "Game Publishing",
  "Game UI designing",
  "Game UX designing",
  "Gameplay Designing",
  "Gameplay Engineering",
  "Gameplay Physics Engineering",
  "Gameplay Testing",
  "Hair Dressing",
  "Influencing",
  "Journalism",
  "Lighting Direction",
  "Marketing",
  "Marketing Coordination",
  "Matte Painting",
  "Meeting Planning",
  "Multimedia Designer",
  "Music Composing",
  "Music Production",
  "Music Publishing",
  "News Casting",
  "News Editing",
  "Orchestra Conduction",
  "Photography",
  "Playback Singing",
  "Professional Gamer",
  "Project Management",
  "Public Relations",
  "Recording Engineering",
  "Resort Management",
  "Retail Events Management",
  "Roto Arts",
  "SFX",
  "Session Music Arts",
  "Sound Engineering",
  "Storyboard/Previsualization",
  "Stunt Direction",
  "Tour Management",
  "Tourism Promotion Manager",
  "Tourism Sales Management",
  "VFX",
  "VR Designer",
  "Vocal Arts",
];
