import type { NextPage } from "next";
import { Box, Button, Typography } from "@mui/material";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <Box p={4} sx={{ minHeight: "100vh" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ marginTop: "10%" }}>
        <Typography color="primary" textAlign="center" variant="h3">
          COMING SOON
        </Typography>
        <Box
          sx={{
            marginTop: "40%",
          }}
        >
          <Typography color="text.primary" textAlign="center">
            from
          </Typography>
          <Typography color="primary" textAlign="center" variant="h5">
            Masuvi Productions
          </Typography>
        </Box>
      </Box>
    </Box>
  );
};

export default Home;
